language: generic
rvm:
 - 2.2
 - generic
os: linux
sudo: required
dist: trusty
matrix:
  fast_finish: true
env:
  global:
    - MAKEJOBS=-j3
    
    matrix:
    - BUILD=win32 HOST=i686-w64-mingw32   DISTNAME=i686-win   PACKAGES="mingw-w64 g++-mingw-w64" BITS=32 MAKEFILE=makefile.linux-mingw BOOST_LIB_SUFFIX="-mt-s" OUTPUT_SUFFIX=".exe" QMAKEOPTS="-xplatform win32-g++" BOOST_THREAD_LIB_SUFFIX="_win32-mt-s"
    - BUILD=win64 HOST=x86_64-w64-mingw32 DISTNAME=x86_64-win PACKAGES="mingw-w64 g++-mingw-w64" BITS=64 MAKEFILE=makefile.linux-mingw BOOST_LIB_SUFFIX="-mt-s" OUTPUT_SUFFIX=".exe" QMAKEOPTS="-xplatform win32-g++" BOOST_THREAD_LIB_SUFFIX="_win32-mt-s"
    - BUILD=macosx HOST=x86_64-apple-darwin14 DISTNAME=x86_64-darwin PACKAGES="clang llvm-dev genisoimage"  BOOST_LIB_SUFFIX="-mt-s" BOOST_THREAD_LIB_SUFFIX="-mt-s" DEPS=deps-osx.tar.xz EXTRADEPS=osxcross.tar.xz
      QMAKE_CXXFLAGS="-I/home/vagrant/deps/SDK/MacOSX10.9/usr/include -DBOOST_HAS_INT128=1" QMAKEOPTS="-xplatform macx-clang-linux" OTOOL=${HOST}-otool INSTALLNAMETOOL=${HOST}-install_name_tool STRIP=${HOST}-strip
    - BUILD=linux64 MAKEFILE=makefile.unix  BOOST_LIB_SUFFIX="-mt" BITS=64
#    - BUILD=macosx MAKEFILE=makefile.osx  BOOST_LIB_SUFFIX="-mt" TODO: osx daemon!!

before_install:
  - sudo apt-get -qq update

install:
  - if [ "$DEPS" == "" ]; then export DEPS=deps-${BUILD}.tar.xz; fi
  - export INDIR=$HOME/inputs
  - export DEPSDIR=$HOME/deps${BITS}
  - export PATH=$DEPSDIR/host/bin:$DEPSDIR:$DEPSDIR/bin:$PATH
  - export QTDIR=$TRAVIS_BUILD_DIR
  - sudo apt-get install build-essential $PACKAGES
  - mkdir -p $INDIR $DEPSDIR
  - cd $INDIR && wget $DEPS_URL/$DEPS `[ "$EXTRADEPS" != "" ] && echo $DEPS_URL/$EXTRADEPS`
  - cd $DEPSDIR && tar xf $INDIR/$DEPS
  - if [ $EXTRADEPS != "" ]; then tar xf $INDIR/$EXTRADEPS; fi
script:
  - echo 'Build Daemon' && echo -en 'travis_fold:start:script.daemon\\r'

  - cd $TRAVIS_BUILD_DIR/src
  - if [ "$MAKEFILE" != "" ]; then make $MAKEJOBS -f $MAKEFILE HOST="$HOST" STATIC=1 OPENSSL_INCLUDE_PATH="$DEPSDIR/include" OPENSSL_LIB_PATH="$DEPSDIR/lib" DEPSDIR="$DEPSDIR" CURDIR="$TRAVIS_BUILD_DIR/src" USE_UPNP=1 BOOST_LIB_SUFFIX="$BOOST_LIB_SUFFIX" DEBUGFLAGS= && install -s Capricoind${OUTPUT_SUFFIX} $INDIR/; fi

  - echo -en 'travis_fold:end:script.daemon\\r'


  - echo 'Build Qt' && echo -en 'travis_fold:start:script.qt\\r'

  - cd $TRAVIS_BUILD_DIR
  - qmake $QMAKEOPTS QMAKE_LRELEASE="$DEPSDIR/host/bin/lrelease" INCLUDEPATH="$DEPSDIR/include" LIBS="-L$DEPSDIR/lib" BOOST_LIB_SUFFIX="$BOOST_LIB_SUFFIX" BOOST_THREAD_LIB_SUFFIX="$BOOST_THREAD_LIB_SUFFIX" RELEASE=1 DEFINES=BOOST_THREAD_USE_LIB QMAKE_CXXFLAGS="-frandom-seed=Capricoin $QMAKE_CXXFLAGS" USE_BUILD_INFO=1 USE_O3=1
  - if [[ "$BUILD" =~ "linux" ]]; then sed -i 's^,-whole-archive -lleveldb -Wl,^,-lleveldb,^' Makefile; fi
  - make $MAKEJOBS

  - echo -en 'travis_fold:end:script.qt\\r'


  - echo 'Package executables' && echo -en 'travis_fold:start:script.package\\r'

  - export BUILD=Otocash_`if [ "$TRAVIS_TAG" != "" ]; then [ "${TRAVIS_TAG:0:1}" == "v" ] && echo ${TRAVIS_TAG:1}_ || echo ${TRAVIS_TAG}_; fi`${BUILD}
  - export UPLOAD=${BUILD}.zip;
  - if [ -d release ]; then cd release; fi
  - if [ -f Otocash${OUTPUT_SUFFIX} ]; then install -s Otocash${OUTPUT_SUFFIX} $INDIR/; export UPLOAD=${BUILD}.zip; fi
  - if [ -d Otocash.app ]; then contrib/macdeploy/createdmg; mv otocash.macosx.dmg $INDIR/${BUILD}.dmg; export UPLOAD=${BUILD}.dmg; fi

  - cd $INDIR
  - if [ -f Otocash${OUTPUT_SUFFIX} ]; then zip $INDIR/$UPLOAD Otocash${OUTPUT_SUFFIX} Otocashd${OUTPUT_SUFFIX}; fi
  - sha256sum $UPLOAD > $INDIR/${UPLOAD}.sha256sum.txt

  - echo -en 'travis_fold:end:script.package\\r'

  - cd $TRAVIS_BUILD_DIR # Need to be in build dir last

after_script:
  - if [ "$TRAVIS_TAG" = "" ]; then travis_retry curl --max-time 60 --upload $INDIR/$UPLOAD https://transfer.sh/$UPLOAD; fi

deploy:
  - provider: releases
  
       file: # Linter thinks this is broken?
      - $INDIR/$UPLOAD
      - $INDIR/${UPLOAD}.sha256sum.txt
    overwrite: true
    on:
      tags: true

